# Generated by Django 5.2.10 on 2026-02-01 03:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('label_text', models.CharField(blank=True, max_length=200)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('ask_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('denomination', models.CharField(blank=True, max_length=60)),
                ('series', models.CharField(blank=True, max_length=120)),
                ('date_mm', models.CharField(blank=True, max_length=20)),
                ('variety', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('holder', models.CharField(blank=True, max_length=20)),
                ('grade_text', models.CharField(blank=True, max_length=40)),
                ('cert_number', models.CharField(blank=True, max_length=40)),
                ('cac_sticker', models.BooleanField(default=False)),
                ('cacg_holder', models.BooleanField(default=False)),
                ('ask_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('IN_STOCK', 'In Stock'), ('AT_GRADING', 'At Grading'), ('LISTED', 'Listed'), ('SOLD', 'Sold'), ('REJECT_BULK', 'Reject/Bulk')], default='IN_STOCK', max_length=20)),
                ('show_location', models.CharField(blank=True, max_length=80)),
                ('cost_basis', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('acquired_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('venue', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('service', models.CharField(choices=[('PCGS', 'PCGS'), ('NGC', 'NGC'), ('CAC', 'CAC'), ('CACG', 'CACG')], max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='PREPARED', max_length=30)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=20)),
                ('grade_text', models.CharField(blank=True, max_length=40)),
                ('cert_number', models.CharField(blank=True, max_length=40)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cert_history', to='portalapp.inventoryitem')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='item_photos/')),
                ('tag', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='portalapp.inventoryitem')),
            ],
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='portalapp.location'),
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_lines', to='portalapp.inventoryitem')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='portalapp.sale')),
            ],
        ),
        migrations.CreateModel(
            name='CrackoutEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_service', models.CharField(blank=True, max_length=20)),
                ('from_grade', models.CharField(blank=True, max_length=40)),
                ('from_cert', models.CharField(blank=True, max_length=40)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('outcome', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crackouts', to='portalapp.inventoryitem')),
                ('to_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crackout_events', to='portalapp.submission')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('declared_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submission_lines', to='portalapp.inventoryitem')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='portalapp.submission')),
            ],
        ),
    ]
