# Generated by Django 5.2.15 on 2026-06-14 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='carrier',
            field=models.CharField(blank=True, choices=[('USPS', 'USPS'), ('FEDEX', 'FedEx'), ('UPS', 'UPS'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='submission',
            name='grading_submission_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='submission',
            name='show_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='submission',
            name='submission_method',
            field=models.CharField(choices=[('SHIPPED', 'Shipped'), ('SHOW_DROPOFF', 'Show Drop-Off')], default='SHIPPED', max_length=20),
        ),
        migrations.AddField(
            model_name='submission',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
