# Generated by Django 5.2.15 on 2026-07-07 16:19

import django.utils.timezone
from django.db import migrations, models


def seed_pricing_plans(apps, schema_editor):
    PricingPlan = apps.get_model('portalapp', 'PricingPlan')
    plans = [
        {
            "name": "Launch",
            "slug": "launch",
            "tagline": "A structured implementation package for an established coin business.",
            "description": "Launch covers configuration, onboarding, and the initial operating setup for CoinPortal 365. It is designed for businesses that need reliable inventory controls, admin workflows, and documented processes before payment activation.",
            "price": "25000.00",
            "billing_interval": "YEAR",
            "display_order": 10,
            "feature_bullets": "12-month platform access\nCore inventory workflow\nLabel printing\nSubmission packet setup\nAdmin pricing configuration\nOperational onboarding support",
        },
        {
            "name": "Growth",
            "slug": "growth",
            "tagline": "Expanded operating support for active dealers with grading and sales volume.",
            "description": "Growth adds submission, sales, and workflow tooling for dealers processing inventory through multiple grading services. It is priced as an annual business software package with clear deliverables and ongoing operational support.",
            "price": "35000.00",
            "billing_interval": "YEAR",
            "display_order": 20,
            "is_featured": True,
            "feature_bullets": "12-month platform access\nEverything in Launch\nPCGS, NGC, CAC, and CACG form workflows\nSale batch workflow\nSubmission status controls\nWorkflow refinement support",
        },
        {
            "name": "Scale",
            "slug": "scale",
            "tagline": "Advanced annual package for teams needing automation and integration planning.",
            "description": "Scale is for organizations that require a deeper implementation, advanced workflow planning, and support for automation initiatives such as invoice intake, reporting, and future integrations. The plan is structured as a 12-month professional software and services engagement.",
            "price": "75000.00",
            "billing_interval": "YEAR",
            "display_order": 30,
            "feature_bullets": "12-month platform access\nEverything in Growth\nInvoice intake planning\nTeam workflow support\nIntegration planning\nAdvanced reporting roadmap\nPriority implementation support",
        },
    ]
    for plan in plans:
        PricingPlan.objects.get_or_create(slug=plan["slug"], defaults=plan)


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0002_add_submission_shipping_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=90, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=160)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('billing_interval', models.CharField(choices=[('MONTH', 'Monthly'), ('YEAR', '12-month'), ('ONE_TIME', 'One-time'), ('CUSTOM', 'Custom')], default='MONTH', max_length=10)),
                ('trial_days', models.PositiveIntegerField(default=0)),
                ('stripe_product_id', models.CharField(blank=True, max_length=120)),
                ('stripe_price_id', models.CharField(blank=True, max_length=120)),
                ('cta_label', models.CharField(default='Contact us', max_length=80)),
                ('cta_url', models.URLField(blank=True)),
                ('feature_bullets', models.TextField(blank=True, help_text='One feature per line.')),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('display_order', 'price', 'name'),
            },
        ),
        migrations.RunPython(seed_pricing_plans, migrations.RunPython.noop),
    ]
