# Generated by Django 5.2.15 on 2026-07-26 01:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0008_restore_choose_plan_cta'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingInventoryBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(blank=True, max_length=160)),
                ('vendor', models.CharField(blank=True, max_length=160)),
                ('invoice_number', models.CharField(blank=True, max_length=80)),
                ('source_file', models.FileField(blank=True, upload_to='incoming_invoices/')),
                ('source_text', models.TextField(blank=True)),
                ('parser_status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PARSED', 'Parsed'), ('REVIEWED', 'Reviewed'), ('IMPORTED', 'Imported'), ('NEEDS_REVIEW', 'Needs Review')], default='UPLOADED', max_length=20)),
                ('parser_notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='IncomingInventoryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('raw_description', models.TextField(blank=True)),
                ('date_mm', models.CharField(blank=True, max_length=20)),
                ('denomination', models.CharField(blank=True, max_length=60)),
                ('series', models.CharField(blank=True, max_length=120)),
                ('variety', models.CharField(blank=True, max_length=120)),
                ('holder', models.CharField(blank=True, max_length=20)),
                ('grade_text', models.CharField(blank=True, max_length=40)),
                ('cert_number', models.CharField(blank=True, max_length=40)),
                ('ask_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cost_basis', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('confidence', models.PositiveSmallIntegerField(default=0)),
                ('needs_review', models.BooleanField(default=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='portalapp.incominginventorybatch')),
                ('imported_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_lines', to='portalapp.inventoryitem')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
