# Generated by Django 5.2.15 on 2026-08-10 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0009_incominginventorybatch_incominginventoryline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='container',
            options={'verbose_name': 'Tube', 'verbose_name_plural': 'Tubes'},
        ),
    ]
