# Generated by Django 5.2.15 on 2026-08-10 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0010_alter_container_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='cac_sticker',
            field=models.BooleanField(default=False, verbose_name='CAC Sticker'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='date_mm',
            field=models.CharField(blank=True, max_length=20, verbose_name='Date / Mint Mark'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='grade_text',
            field=models.CharField(blank=True, max_length=40, verbose_name='Grade'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='holder',
            field=models.CharField(blank=True, max_length=20, verbose_name='Grading Company'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='internal_id',
            field=models.CharField(blank=True, help_text='Leave blank to generate automatically.', max_length=20, unique=True, verbose_name='Internal ID'),
        ),
    ]
