# Generated by Django 5.2.15 on 2026-08-10 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0011_alter_inventoryitem_cac_sticker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='cert_number',
            field=models.CharField(blank=True, max_length=40, verbose_name='Cert Number'),
        ),
    ]
