# Generated by Django 5.2.15 on 2026-08-10 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0012_alter_inventoryitem_cert_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleTube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tube_lines', to='portalapp.sale')),
                ('tube', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_lines', to='portalapp.container')),
            ],
        ),
    ]
