# Generated by Django 5.2.15 on 2026-08-10 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0013_saletube'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incominginventorybatch',
            options={'ordering': ('-created_at',), 'verbose_name': 'Incoming inventory batch', 'verbose_name_plural': 'Incoming inventory batches'},
        ),
    ]
