# Generated by Django 5.2.15 on 2026-08-10 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0014_alter_incominginventorybatch_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='internal_id',
            field=models.CharField(blank=True, help_text='Leave blank to generate automatically.', max_length=20, unique=True, verbose_name='Internal ID'),
        ),
    ]
