# Generated by Codex on 2026-09-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portalapp", "0015_alter_container_internal_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="container",
            name="date_mm",
            field=models.CharField(blank=True, max_length=20, verbose_name="Date / Mint Mark"),
        ),
        migrations.AddField(
            model_name="container",
            name="denomination",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="container",
            name="series",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
