# Generated by Codex on 2026-09-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portalapp", "0016_container_coin_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="container",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
