# Generated by Codex on 2026-09-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portalapp", "0017_alter_container_quantity"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
            options={
                "verbose_name": "Report",
                "verbose_name_plural": "Reports",
                "managed": False,
            },
        ),
    ]
