# Generated by Codex on 2026-09-05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portalapp", "0018_report"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "internal_id",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank to generate automatically.",
                        max_length=20,
                        unique=True,
                        verbose_name="Product ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("sku", models.CharField(blank=True, max_length=80, verbose_name="SKU")),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("unit_price", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="portalapp.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ("name", "internal_id"),
            },
        ),
    ]
