# Generated by Codex on 2026-09-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portalapp", "0019_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="container",
            name="cost_basis",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Cost",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="cost_basis",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Cost",
            ),
        ),
    ]
