# Generated by Codex on 2026-09-06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portalapp", "0020_container_product_cost_basis"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inventoryitem",
            options={"verbose_name": "Inventory", "verbose_name_plural": "Inventory"},
        ),
        migrations.CreateModel(
            name="NumismaticItem",
            fields=[],
            options={
                "verbose_name": "Numismatic",
                "verbose_name_plural": "Numismatic",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("portalapp.inventoryitem",),
        ),
    ]
