# Generated by Codex on 2026-09-07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portalapp", "0021_inventory_numismatic_proxy"),
    ]

    operations = [
        migrations.CreateModel(
            name="RawItem",
            fields=[],
            options={
                "verbose_name": "Raw",
                "verbose_name_plural": "Raw",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("portalapp.inventoryitem",),
        ),
    ]
