# Generated by Codex on 2026-09-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portalapp", "0022_rawitem_proxy"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="inventoryitem",
            index=models.Index(fields=["status", "created_at"], name="inv_status_created_idx"),
        ),
        migrations.AddIndex(
            model_name="inventoryitem",
            index=models.Index(fields=["holder"], name="inv_holder_idx"),
        ),
        migrations.AddIndex(
            model_name="inventoryitem",
            index=models.Index(fields=["date_mm"], name="inv_date_mm_idx"),
        ),
        migrations.AddIndex(
            model_name="inventoryitem",
            index=models.Index(fields=["cert_number"], name="inv_cert_idx"),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(fields=["status", "created_at"], name="sub_status_created_idx"),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(fields=["service"], name="sub_service_idx"),
        ),
        migrations.AddIndex(
            model_name="container",
            index=models.Index(fields=["created_at"], name="tube_created_idx"),
        ),
        migrations.AddIndex(
            model_name="container",
            index=models.Index(fields=["date_mm"], name="tube_date_mm_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["sku"], name="prod_sku_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["updated_at"], name="prod_updated_idx"),
        ),
    ]
